### ISSUE TITLE
Few questions 

### ISSUE THREAD

**Issue by bignaux** [szieke/ScriptCommunicator_serial-terminal#22]
cheetahSpi/cheetah.so seems to have no source file, what's the deal ?
aardvark.so is not build with the latest release, is that normal ? (only have aardvarkI2cSpi.o  aardvark.o ).
why don't put sources at folder root on the github repo ?
Can you explicit Qt5DesignerComponents customization and how we can build it, it seems to be hard to make all this work :)

I'm fixing my package for nixos https://github.com/NixOS/nixpkgs/pull/36747

**Comment by szieke** [comment]
Hi,
cheetah SPI is a device which is not supported by ScriptCommunicator anymore. I forgot to remove the cheetahSpi folder.
The aardvark I2c Spi device is only supported on Windows and here the corresponding object file is built.
"why don't put sources at folder root on the github repo": Because I wanted to separate the source from the project description file (README.md).
What do you exactly mean with Qt5DesignerComponents customization?

**Comment by bignaux** [comment]
Thanks for information about SPI drivers. Latest about Qt5DesignerComponents you write in readme "- the Qt5DesignerComponents library (is customized for ScriptCommunicator, can be found in ./designer/'plattform name')" but i would know what, if it is not a not anymore relevant comment.

**Comment by szieke** [comment]
Hi,

The QtDesigner executable in the ScripCommunictor folder uses the Qt5DesignerComponents library (it contains the standard Qt widgets which can be used in the QtDesigner). 
I have customized the standard Qt5DesignerComponents library because ScriptCommunicator doesn't support all Qt standard widgets (I removed all not supported widgets). 
But this was years ago and I don't know anymore how I have done this. But you can just add the standard Qt5DesignerComponents  library to the ScriptCommunicator folder from your Qt installation. 
If you add a not supported Qt widget to a user interface file in the QtDesigner then ScriptCommunicator will not load the corresponding script and show a message box.

**Comment by bignaux** [comment]
Thanks for the clear answer.
